development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://fayserver-chatapp.herokuapp.com/faye"
  secret_token: "chatappprototype"
  signature_expiration: 86400 # one day
